### PR TITLE
fix: exporting of empty scripts now works properly

### PR DESCRIPTION
**Pull request by meesvandongen**
Resubmission of #388

basically only adds `nodeObject.script !== emptyScript` check.

Rest of the changes is awaiting some promises to prevent unhandled promise rejections.

### CODE REVIEW

**Comment by vscheuber** [comment]
@meesvandongen can you remove all unrelated files from the PR? You should not be updating package.json or package-lock.json or app.js. I will review the proposed changes. I did see one immediate concern, which is the change to ScriptApi.js. All APIs should be async in nature and return promises. So that change is likely to be rejected.

What would help is if you could describe to me quickly what how to reproduce the issue, as I have not encountered it and am not sure how to reproduce it and how to add regression tests for it.

**Comment by meesvandongen** [comment]
@vscheuber In journeys, in my `nodePromises` there end up some objects that look like this
```json
{
  "_id": "1d84192f-82be-458a-977f-4cdbd6df6720",
  "_rev": "1195589687",
  "script": "[Empty]",
  "outcomes": [],
  "outputs": [
    "*"
  ],
  "inputs": [
    "*"
  ],
  "_type": {
    "_id": "ScriptedDecisionNode",
    "name": "Scripted Decision",
    "collection": true
  },
  "_outcomes": []
}
```

Later, this object is used like this:
```js
scriptPromises.push(getScript(nodeObject.script));
```
to construct a URL.

Now, it seems like "incomplete" scripts exist in the DB.
image

Here, the "Script" selection is not set for these nodes. I think this is still a valid use case as it is possible to end up in the database like that.

---
The edit to main.js is not directly relevant to the issue; but when the program encounters a Promise it cannot handle, it will never go to the catch() phase in main, as not all promises are awaited properly, including in main.js. IMO TypeScript will help here, might be something worth considering. As you are moving to 2 repo setup a build step is not out of reach. Eslint typescript has a rule "no floating promises".

**Comment by vscheuber** [comment]
@meesvandongen we are moving to the new code base in the rockcarver/frodo-lib and rockcarver/frodo-cli repositories and thus I will not merge this PR but I have consumed pretty much all of it into the new code base.

Oh! Could you tell me your real name and email address? Your github profile does not give anything away and I feel like I might want to reach out to you directly and I can't shake off the feeling that I might know you without knowing ;)

**Comment by meesvandongen** [comment]
@vscheuber Mees van Dongen is my real name, meesvandongen@gmail.com is my email.

**Pull request closed without merging**
